spring:
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
      sampler:
        probability: 1.0

server:
  servlet:
    contextPath: /auth
  port: 8787


eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/discovery/eureka
      register-with-eureka: true
      fetch-registry: true

management:
  info:
    env:
      enabled: true
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: prometheus,health,info

