spring:
  application:
    name: customer
  r2dbc:
    url: r2dbc:mysql://localhost:3306/customers
    username: root

server:
  servlet:
    contextPath: /customers
  port: 8182

logging:
  level:
    org:
      springframework:
        r2dbc: INFO

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/discovery/eureka
      register-with-eureka: true
      fetch-registry: true
