
#spring:
#  webflux:
#    base-path: /customers
#  r2dbc:
#    url: r2dbc:mysql://localhost:3306/customers
#    username: root
#    password: 123456
 # zipkin:
 #   baseUrl: http://localhost:9411
 #   sleuth:
 #     sampler:
 #       percentage: 1.0

  #info.build.artifact=@project.artifactId@
  #info.build.version=@project.version@

spring:
  application:
    name: customer
  datasource:
    url: jdbc:mysql://192.168.1.44:3306/customers?serverTimezone=Asia/Bangkok
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connectionTimeout: 10000
      idleTimeout: 10000
      maxLifetime: 1800000
      initializationFailTimeout: -1
      maximumPoolSize: 5
      minimumIdle: 1
zipkin:
  tracing:
    endpoint: http://localhost:9411/api/v2/spans
  sleuth:
      sampler:
        probability: 1.0

server:
  servlet:
    contextPath: /customers
  port: 8011

logging:
  level:
    org:
      springframework:
        r2dbc: INFO
  sensitive:
    enabled: true
    keys:
      mobile_number: MASKING
      email: MASKING
      first_name: MASKING
      last_name: MASKING
      password: HIDDEN
    masking-size: 4

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/discovery/eureka
      register-with-eureka: true
      fetch-registry: true

management:
  info:
    env:
      enabled: true
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: prometheus,health,info

masking:
  masking-keys:
    - mobile_number
    - email
    - first_name
    - last_name
  masking-size: 4

