spring:
  application:
    name: customer-service
  r2dbc:
    url: r2dbc:mysql://localhost:3306/customers
    username: root
server:
  servlet:
    contextPath: /customers
  port: 8011

logging:
  level:
    org:
      springframework:
        r2dbc: INFO

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}
