spring:
  application:
    name: employee
  data:
    mongodb:
      host: 192.168.1.124
      port: 27017
      database: company
      repositories:
        enabled: true
  cloud:
    config:
      override-system-properties: false
      allow-override: true
      override-none: true
      discovery:
        enabled: true
  sleuth: #add this
    sampler:
      probability: 1.0

server:
  servlet:
    contextPath: /employee
  port: 8182

eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.124:9001/eureka
      register-with-eureka: true
      fetch-registry: true
