spring:
  application:
    name: employee
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      username: root
      password: secret
      database: company
      repositories:
        enabled: true
  cloud:
    config:
      override-system-properties: false
      allow-override: true
      override-none: true
      discovery:
        enabled: true
  sleuth: #add this
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411/

server:
  servlet:
    contextPath: /employee
  port: 8182

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka
      register-with-eureka: true
      fetch-registry: true
