spring:
  application:
    name: gateway
  main:
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      default-filters:
        - name: EncryptDecryptFilter
      routes:
        - id: customer
          uri: lb://CUSTOMER
          predicates:
            - Path=/customers/**
  zipkin.baseUrl: http://localhost:9411
  sleuth.sampler.percentage: 1

logging:
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE

server:
  port: 80

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/discovery/eureka/

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: prometheus