server:
  port: 8012

spring:
  webflux:
    base-path: /products
  r2dbc:
    url: r2dbc:mysql://localhost:3306/products
    username: root

logging:
  level:
    org:
      springframework:
        r2dbc: INFO

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/discovery/eureka
      register-with-eureka: true
      fetch-registry: true

management:
  info:
    env:
      enabled: true
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: prometheus,health,info
